/**
 * 全量样式入口
 * 仅包含主题 Token 与各组件样式，不包含任何 JS 逻辑。
 */
import './theme/tokens.scss'
import './theme/semantic.scss'
import './theme/themes/light.scss'
import './theme/themes/dark.scss'
import './theme/themes/soft.scss'
import './theme/themes/cyber.scss'

import './components/button/style.scss'
import './components/icon/style.scss'
import './components/space/style.scss'
import './components/divider/style.scss'
import './components/card/style.scss'
import './components/tag/style.scss'
import './components/input/style.scss'
import './components/form/style.scss'
import './components/form-item/style.scss'
import './components/modal/style.scss'
import './components/drawer/style.scss'
import './components/container/style.scss'
import './components/skeleton/style.scss'
import './components/tabs/style.scss'
import './components/select/style.scss'
import './components/cascader/style.scss'
import './components/upload/style.scss'
import './components/pagination/style.scss'
import './components/table/style.scss'
import './components/watermark/style.scss'
import './components/layout/style.scss'
